add_executable(plouvain cluster_main.cpp)
add_executable(pleiden cluster_main.cpp)
add_executable(pleiden+ cluster_main.cpp)
add_executable(meme memetic_clustering.cpp)
add_executable(verify_mod verify_modularity.cpp)

foreach(prog plouvain pleiden pleiden+ verify_mod meme)
    target_include_directories(${prog} PRIVATE ${CMAKE_SOURCE_DIR}/header ${CMAKE_SOURCE_DIR}/src)
endforeach(prog)

target_compile_definitions(pleiden PUBLIC LEIDEN)
target_compile_definitions(pleiden+ PUBLIC LEIDEN LEIDEN_PLUS)
target_compile_definitions(meme PUBLIC LEIDEN_PLUS)
foreach(prog plouvain pleiden pleiden+ verify_mod meme)
    target_link_libraries(${prog} Kokkos::kokkos Kokkos::kokkoskernels)
endforeach()
